name: Code Quality

on:
  pull_request:
    branches:
      - master

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Hatch
        uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5

      - name: Run checks
        run: |
          hatch fmt --check
  unit-test:
    name: Unit Test
    needs: [format-check]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5

      - name: Run tests
        if: ${{ matrix.python-version != '3.13' }}
        run: |
          hatch test -i python=${{ matrix.python-version }}

      - name: Run tests with coverage
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          hatch test --cover -i python=${{ matrix.python-version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}